djblogger/api/urls.py
from django.urls import path
from .views import articles_collection

urlpatterns = [
    path('articles', articles_collection, name='articles_collection')
]

djblogger/articles/urls.py
from django.urls import path
from .views import article, create_article

app_name = 'articles'

urlpatterns = [
    path('<int:article_id>/', article.as_view(), name='article'),
    path('create/', create_article.as_view(), name='create')
]

djblogger/djblogger/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from users.views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('articles.urls')),
    path('user/', include('users.urls')),
    path('api/', include('api.urls')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    url('^ckeditor/', include('ckeditor_uploader.urls')),
]

# serve /media/ during development.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djblogger/articles/models.py
from django.db import models
from users.models import Author
from ckeditor_uploader.fields import RichTextUploadingField


class Article(models.Model):
    title = models.CharField(max_length=200, blank=False, null=False)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="articles")
    poster = models.ImageField(verbose_name="poster")
    content = RichTextUploadingField(blank=False,null=False, default="<h1>Empty Article !!!</h1>")

    def __str__(self):
        return f"{self.title} @ {self.date_created} by {self.author}"

djblogger/articles/forms.py
from django import forms
from .models import Article
from django.contrib.auth import get_user
from django.contrib.auth.models import User

class ArticleContent(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'poster']

djblogger/articles/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, get_user, login, logout
from django.contrib.auth.models import User
from django.views import View
from .models import Article
from users.models import Author
from .forms import ArticleContent

class article(View):
    def get(self, request, article_id):
        art = None
        art = Article.objects.filter(id = article_id).first()
        if art == None :
            # tdoo : 
            return render(request, "default/articlenotfound.html", {
                'id':article_id
            })
        return render(request, 'default/viewer.html', {
            'title' : art.title,
            'author' : art.author,
            'date_created' : art.date_created,
            'content' : art.content,
            'poster' : art.poster.url
        })

class create_article(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('login'))

        return render(request, 'default/addarticle.html', {
            'form' : ArticleContent(),
            'message' : 'enter information then press save'
        })
    
    def post(self, request):
        if(request.method != "POST"):
            # todo : do something better !!!
            return HttpResponse("ERROR !!!")
        
        form_content = ArticleContent(request.POST, request.FILES)
        
        if not form_content.is_valid():
            return render(request, 'default/addarticle.html', {
                'form' : ArticleContent(),
                'message' : 'invalid information !!'
            })

        art = form_content.save(commit=False)
        art.author = Author.objects.get(user = request.user)
        art.save()

        return HttpResponseRedirect(reverse('articles:article', args=(art.id, )))

djblogger/articles/templates/default/addarticle.html
{% load static %}
{% comment %} inputs : form, message {% endcomment %}
<!DOCTYPE html>
<html>
    <head>
        <title>testing ckeditor in django</title>
    </head>
    <body>
        <form action="{% url 'articles:create' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form}}
        <input type='submit' value='save'>
        </form>
        <br>
        {{message}}
    </body>
</html>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

djblogger/articles/templates/default/articlenotfound.html
<!DOCTYPE html>
<html>
    <head>
        <title>testing ckeditor in django</title>
    </head>
    <body>
        <h1><b>404</b></h1>
        <h4>article with id {{id}} not found !!!</h4>
    </body>
</html>

djblogger/articles/templates/default/login.html
{% comment %} inputs : message {% endcomment %}
<!DOCTYPE html>
<html>
    <head>
        <title>logging in</title>
    </head>
    <body>
        {{message}}<br>
		<form action="{% url 'login' %}" method ="POST">
        {% csrf_token %}
        <label for='username'>Username : </label>
        <input type='text' name='username'><br>
        <label for='password'>Password : </label>
        <input type='password' name='password'><br>
        <input type="submit" value="login">
        </form>
    </body>
</html>

djblogger/articles/templates/default/viewer.html
{% comment %} inputs : title, author, date_created, content, poster {% endcomment %}
<!DOCTYPE html>
<html>
    <head>
        <title>testing ckeditor in django</title>
    </head>
    <body>
		<img src="{{poster}}" >
		<h1>{{title}}</h1>
		<p>author : {{author}}</p>
		<p>creation date : {{date_created}}</p>
		<hr>
		{% autoescape off %}
			{{content}}
		{% endautoescape %}
    </body>
</html>